2016/10/02 17:42:08 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/02 17:42:18 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/02 17:42:20 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/02 17:43:35 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/02 17:43:42 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/contact
---
2016/10/02 17:43:55 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(30): CActiveForm->textField(Object(Users), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/contact
---
2016/10/02 18:28:44 [error] [exception.CException] exception 'CException' with message 'Property "Users.verifyCode" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('verifyCode')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('verifyCode')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'verifyCode')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'verifyCode', Array)
#4 C:\xampp\htdocs\newTest\protected\views\users\index.php(43): CHtml::activeTextField(Object(Users), 'verifyCode')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(24): CController->render('index', Array)
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/contact
---
2016/10/02 19:17:34 [error] [exception.CException] exception 'CException' with message 'Users and its behaviors do not have a method or closure named "check".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(227): CComponent->__call('check', Array)
#1 C:\xampp\htdocs\newTest\protected\components\UserIdentity.php(27): CActiveRecord->__call('check', Array)
#2 C:\xampp\htdocs\newTest\protected\components\UserIdentity.php(27): Users->check('wowowow')
#3 C:\xampp\htdocs\newTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\newTest\protected\controllers\SiteController.php(94): CModel->validate()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/newTest/index.php/site/login
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
2016/10/02 20:07:49 [error] [php] include(Mail.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): spl_autoload_call()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (21)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/02 20:11:20 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'tenni' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (19)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/02 20:11:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'tenni' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(19): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:11:50 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.email" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(105): CComponent->__get('email')
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): CModule->__get('email')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:14:09 [error] [exception.CException] exception 'CException' with message 'Alias "application.extensions.email.Email" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php(196): YiiBase::import('application.ext...', true)
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(103): CModule->getComponent('email')
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): CModule->__get('email')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:21:37 [error] [exception.CException] exception 'CException' with message 'Alias "application.extensions.email.Email" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php(196): YiiBase::import('application.ext...', true)
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(103): CModule->getComponent('email')
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): CModule->__get('email')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:22:36 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1124' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (19)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/02 20:22:36 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1124' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(19): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:26:53 [error] [exception.CException] exception 'CException' with message 'Alias "application.extensions.yii-mail" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php(196): YiiBase::import('application.ext...', true)
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(103): CModule->getComponent('email')
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): CModule->__get('email')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:27:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '213' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (19)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/02 20:27:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '213' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`) VALUES (:yp0, :yp1, :yp2)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(19): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:27:56 [error] [exception.CException] exception 'CException' with message 'Alias "application.extensions.email.Email" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php(196): YiiBase::import('application.ext...', true)
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(103): CModule->getComponent('email')
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(21): CModule->__get('email')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/02 20:49:50 [error] [exception.CHttpException.500] exception 'CHttpException' with message 'something went horrible wrong' in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:30
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#7 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/03 00:18:36 [error] [php] include(YiiMailMessage.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(22): spl_autoload_call()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (22)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 00:24:15 [error] [php] include(YiiMailMessage.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(22): spl_autoload_call()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (22)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 00:26:40 [error] [exception.CException] exception 'CException' with message 'Users and its behaviors do not have a method or closure named "from".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(227): CComponent->__call('from', Array)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(30): CActiveRecord->__call('from', Array)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(30): Users->from('registration@ma...')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/03 00:27:40 [error] [exception.CException] exception 'CException' with message 'YiiMailMessage and its behaviors do not have a method or closure named "from".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMailMessage.php(91): CComponent->__call('from', Array)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(30): YiiMailMessage->__call('from', Array)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(30): YiiMailMessage->from('registration@ma...')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/users
---
2016/10/03 00:28:28 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(32): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 00:37:29 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(32): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 00:40:31 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 01:58:21 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 01:59:28 [error] [php] Array to string conversion (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\MailTransport.php:173)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\MailTransport.php (173)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php (77)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php (133)
2016/10/03 02:14:27 [error] [php] Array to string conversion (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\MailTransport.php:173)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\MailTransport.php (173)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php (77)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php (133)
2016/10/03 02:19:21 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\SimpleMailInvoker.php:50)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(77): Swift_MailTransport->send()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\SimpleMailInvoker.php (50)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\MailTransport.php (173)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php (77)
2016/10/03 02:22:35 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 02:28:03 [error] [php] fsockopen(): php_network_getaddresses: getaddrinfo failed: No such host is known.  (C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php:233)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php(101): Swift_Transport_StreamBuffer->initialize()
#1 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Mailer.php(74): Swift_SmtpTransport->start()
#2 C:\xampp\htdocs\newTest\protected\extensions\yii-mail\YiiMail.php(133): Swift_Mailer->send()
#3 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(33): YiiMail->send()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (233)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\StreamBuffer.php (70)
in C:\xampp\htdocs\newTest\protected\extensions\yii-mail\vendors\swiftMailer\classes\Swift\Transport\AbstractSmtpTransport.php (101)
2016/10/03 04:01:14 [error] [php] require(../vendor/autoload.php): failed to open stream: No such file or directory (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:4)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(276): CWebApplication->createController()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#3 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (4)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (4)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 04:06:02 [error] [php] require_once(C:\xampp\htdocs\newTest\protected../vendor/autoload.php): failed to open stream: No such file or directory (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:4)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(276): CWebApplication->createController()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#3 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (4)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (4)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 04:13:43 [error] [php] include(PHPMailer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(9): spl_autoload_call()
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(53): UsersController->sentEmail()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (9)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (53)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 04:15:31 [error] [php] include(PHPMailer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(9): spl_autoload_call()
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(53): UsersController->sentEmail()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (9)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (53)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 04:44:56 [error] [php] include(PHPMailer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(9): spl_autoload_call()
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(53): UsersController->sentEmail()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (9)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (53)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 04:49:59 [error] [php] Use of undefined constant email - assumed 'email' (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:13)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (13)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (53)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/03 13:03:12 [error] [exception.CException] exception 'CException' with message 'UsersController cannot find the requested view "register".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('register', Array, true)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(59): CController->render('register', Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/index
---
2016/10/03 13:03:50 [error] [exception.CException] exception 'CException' with message 'UsersController cannot find the requested view "register".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('register', Array, true)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(59): CController->render('register', Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
2016/10/03 13:05:15 [error] [exception.CException] exception 'CException' with message 'UsersController cannot find the requested view "register".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('register', Array, true)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(59): CController->render('register', Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
2016/10/03 13:05:38 [error] [exception.CException] exception 'CException' with message 'UsersController cannot find the requested view "register".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('register', Array, true)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(59): CController->render('register', Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users/index
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
2016/10/03 13:48:00 [error] [exception.CException] exception 'CException' with message 'Property "Users.verifyCode" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('verifyCode')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CActiveRecord->__get('verifyCode')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(Users), 'verifyCode')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(Users), 'verifyCode', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(Users), 'verifyCode', Array)
#5 C:\xampp\htdocs\newTest\protected\views\users\index.php(45): CActiveForm->textField(Object(Users), 'verifyCode')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(46): CController->render('index', Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#17 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/newTest/index.php/users/index
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
2016/10/03 22:15:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(2386): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(36): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/04 01:52:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(2386): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Users))
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(36): CActiveRecord->__construct()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/newTest/index.php/users/index
---
2016/10/04 11:14:26 [error] [exception.CException] exception 'CException' with message 'Property "Users.validate" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('validate')
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(45): CActiveRecord->__get('validate')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users/index
HTTP_REFERER=http://localhost/newTest/index.php/users/index
---
2016/10/04 11:14:56 [error] [exception.CException] exception 'CException' with message 'Property "Users.save" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(145): CComponent->__get('save')
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(46): CActiveRecord->__get('save')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('index')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/index')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users/index
HTTP_REFERER=http://localhost/newTest/index.php/users/index
---
2016/10/04 11:15:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
HTTP_REFERER=http://localhost/newTest/index.php/users/index
---
2016/10/04 11:15:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
HTTP_REFERER=http://localhost/newTest/index.php/users/index
---
2016/10/04 11:23:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:23:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:23:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:23:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:25:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 11:36:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:05:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/newTest/index.php/user
---
2016/10/04 12:05:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 12:07:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/users/success
---
2016/10/04 12:10:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:10:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:32:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:33:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:33:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "activation".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('activation')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('activation')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/activation')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/activation
---
2016/10/04 12:33:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "success".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(270): CController->missingAction('success')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('success')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/success')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/newTest/index.php/site/success
---
2016/10/04 13:08:57 [error] [exception.CException] exception 'CException' with message 'UsersController cannot find the requested view "index".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php:878
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#1 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(56): CController->render('index', Array)
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/site/index
---
2016/10/04 13:43:08 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:43:08 [error] [php] Object of class Users could not be converted to string (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:126)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (126)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:43:31 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:48:24 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:50:44 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:53:44 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 13:53:51 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:29:32 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:30:09 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:30:22 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:30:22 [error] [php] Object of class Users could not be converted to string (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:126)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (126)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:30:36 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:30:51 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (124)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:37:09 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:39:12 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:39:24 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:39:24 [error] [php] Object of class Users could not be converted to string (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:101)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:40:40 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:40:40 [error] [php] Object of class Users could not be converted to string (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:101)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:40:49 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:40:53 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:43:29 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:45:18 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:45:33 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:45:33 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:106)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (106)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:45:57 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:45:57 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:107)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (107)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:46:03 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:46:31 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:48:55 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:49:01 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:49:52 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:51:20 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:51:33 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:52:03 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:53:29 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:53:43 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (98)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:58:38 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:105)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (105)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 16:59:22 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:105)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (105)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:01:08 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:01:08 [error] [php] Object of class Users could not be converted to string (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:104)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?activation=3b002881924b0a77645ecc9fa6bda931&email=nadalfederer%40mail.ru
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (104)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:01:15 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:02:14 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:02:31 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:03:17 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:03:25 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:03:28 [warning] [application] Failed to set unsafe attribute "activation" of "Users".
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (101)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:16:09 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sg' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (48)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:16:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sg' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(48): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/users/register
---
2016/10/04 17:28:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sdga' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (48)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:28:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sdga' for key 'username'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(48): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/users/register
---
2016/10/04 17:34:26 [error] [exception.CException] exception 'CException' with message 'Users and its behaviors do not have a method or closure named "exist".' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(227): CComponent->__call('exist', Array)
#1 C:\xampp\htdocs\newTest\protected\models\Users.php(49): CActiveRecord->__call('exist', Array)
#2 C:\xampp\htdocs\newTest\protected\models\Users.php(49): Users->exist('username=:usern...', Array)
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CInlineValidator.php(42): Users->validateUsername('username', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Users), 'username')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModel.php(159): CValidator->validate(Object(Users), NULL)
#6 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(45): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/users/register
---
2016/10/04 17:36:23 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='. The SQL statement executed was: SELECT 1 FROM `users` `t` WHERE username=:username LIMIT 1.
in C:\xampp\htdocs\newTest\protected\models\Users.php (50)
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (45)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 17:36:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='. The SQL statement executed was: SELECT 1 FROM `users` `t` WHERE username=:username LIMIT 1' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1675): CDbCommand->queryRow()
#2 C:\xampp\htdocs\newTest\protected\models\Users.php(50): CActiveRecord->exists('username=:usern...', Array)
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CInlineValidator.php(42): Users->validateUsername('username', Array)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Users), 'username')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CModel.php(159): CValidator->validate(Object(Users), NULL)
#6 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(45): CModel->validate()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/users/register
---
2016/10/04 17:49:08 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.логин" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CComponent->__get('\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD', Array)
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD', Array)
#4 C:\xampp\htdocs\newTest\protected\views\site\login.php(29): CActiveForm->textField(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\newTest\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/newTest/index.php/site/login
HTTP_REFERER=http://localhost/newTest/index.php
---
2016/10/04 17:49:17 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.логин" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2729): CComponent->__get('\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(2452): CHtml::resolveValue(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\helpers\CHtml.php(1534): CHtml::activeInputField('text', Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD', Array)
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD', Array)
#4 C:\xampp\htdocs\newTest\protected\views\site\login.php(29): CActiveForm->textField(Object(LoginForm), '\xD0\xBB\xD0\xBE\xD0\xB3\xD0\xB8\xD0\xBD')
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\xampp\htdocs\newTest\protected\controllers\SiteController.php(93): CController->render('login', Array)
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/newTest/index.php/site/login
HTTP_REFERER=http://localhost/newTest/index.php
---
2016/10/04 18:26:00 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'password'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (48)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 18:26:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'password'. The SQL statement executed was: INSERT INTO `users` (`username`, `password`, `email`, `activation`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\newTest\protected\controllers\UsersController.php(48): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): UsersController->actionRegister()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('register')
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('users/register')
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/newTest/index.php/users/register
HTTP_REFERER=http://localhost/newTest/index.php/users/register
---
2016/10/04 20:59:44 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\newTest\protected\controllers\UsersController.php:112)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): UsersController->runAction()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): UsersController->runActionWithFilters()
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): UsersController->run()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php/users/activate?email=nadalfederer%40mail.ru&activation=d5b9a14cc1059c4b15f8c8f6c235b847
in C:\xampp\htdocs\newTest\protected\controllers\UsersController.php (112)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 21:05:21 [error] [php] Object of class CWebUser could not be converted to string (C:\xampp\htdocs\newTest\protected\views\site\index.php:8)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\newTest\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\newTest\index.php(13): CWebApplication->run()
REQUEST_URI=/newTest/index.php
in C:\xampp\htdocs\newTest\protected\views\site\index.php (8)
in C:\xampp\htdocs\newTest\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\newTest\index.php (13)
2016/10/04 21:05:32 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 C:\xampp\htdocs\newTest\protected\views\site\index.php(8): CWebUser->__get('username')
#2 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\newTest\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(282): CController->run('')
#12 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii-1.1.17.467ff50\yii-1.1.17.467ff50\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\newTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/newTest/index.php
HTTP_REFERER=http://localhost/newTest/index.php/site/login
---
